"""add phone Number

Revision ID: 3e41e15dd5d6
Revises: e31553f1ddfc
Create Date: 2023-11-08 22:56:13.671952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e41e15dd5d6'
down_revision: Union[str, None] = 'e31553f1ddfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comment')
    # ### end Alembic commands ###
