"""Restruc Posts Table

Revision ID: dea5c5316860
Revises: 8ed1a6ed3188
Create Date: 2023-11-09 22:56:48.915697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea5c5316860'
down_revision: Union[str, None] = '8ed1a6ed3188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
